---
- name: install nginx
  dnf:
    name: nginx
    state: latest
    update_cache: yes

- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: allow firewall to accept http traffic
  firewalld:
    service: http
    permanent: yes
    state: enabled
