name: Build Frontend
on: [pull_request, workflow_dispatch]
defaults:
  run:
    working-directory: front

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposotory
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build and Test
        run: |
          npm install
          npm run test:ci
          npm run build
